title: "Sumi Elizabeth Joseph"
description: "AI & Product Leadership Portfolio"
url: "https://ejsumi.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # options: air, contrast, dark, dirt, neon, mint, plum, sunrise

# Author profile
author:
  name: "Sumi Elizabeth Joseph"
  avatar: "/assets/images/avatar.jpg"
  bio: "AI & Product Leader | Knowledge & Content Management | GenAI Solutions"
  location: "Bangalore, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sumi-elizabeth-joseph/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ejsumi"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sumiej12@gmail.com"

# Navigation menu
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings for cleaner URLs
permalink: /:categories/:title/

# Default layout settings for pages/posts
defaults:
  # All pages in _pages folder
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # Blog posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Navigation links
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single

# Social sharing
twitter_username: ""
github_username: ejsumi

# Exclude unnecessary files from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

