title: "Sumi Elizabeth Joseph"
description: "AI & Product Leadership Portfolio"
url: "https://ejsumi.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
# Minimal Mistakes skin
minimal_mistakes_skin: "default"

# Author profile
author:
  name: "Sumi Elizabeth Joseph"
  avatar: "/assets/images/avatar.jpg"
  bio: "AI & Product Leader | Knowledge & Content Management | GenAI Solutions"
  location: "Bangalore, India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/sumi-elizabeth-joseph/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ejsumi"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sumiej12@gmail.com"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  learnings:
    output: true
    permalink: /learnings/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: learnings
    values:
      layout: single
      author_profile: true
