title: "Sumi Elizabeth Joseph"
description: "AI & Product Leadership Portfolio"
url: "https://ejsumi.github.io"
remote_theme: "mmistakes/minimal-mistakes"

# Pagination
paginate: 10
paginate_path: "/page:num/"
timezone: Asia/Kolkata

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache
  
# Minimal Mistakes skin
minimal_mistakes_skin: "default"


category_archive:
  type: liquid
  path: /categories/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages

collections:
  pages:
    output: true